name: Go

on:
  push: 
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16', '1.18' ]
    name: Go Version ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt-get install -y gnutls-bin softhsm2

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: make

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1

    - name: Test
      run: make test
